[project]
name = "rheofit"
version = "1.0.0"
description = "Python library for rheology data analysis"
authors = [{name = "Marco Caggioni", email = "marco.caggioni@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.9"
dependencies = [
    "lmfit",
    "xmltodict",
    "emcee",
    "corner",
    "pybroom",
    "xlrd",
    "ipywidgets",
    "numpy",
    "pandas",
    "matplotlib",
    "openpyxl",
    "ipykernel>=6.31.0",
    "seaborn>=0.13.2",
    "tadatakit>=0.1.1",
    "tqdm>=4.67.3",
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "nbsphinx",
]
dev = [
    "pytest",
]

[project.urls]
Home = "https://github.com/rheopy/rheofit"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["rheofit"]
